{
  "language": "node_js",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "node_js": [
    "10",
    "12",
    "14"
  ],
  "services": [
    "mongodb"
  ],
  "cache": {
    "directories": [
      "node_modules"
    ]
  },
  "install": [
    "npm install"
  ],
  "script": [
    "npm run lint",
    "npm test"
  ]
}